/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MarcheRouteImport } from './routes/marche'
import { Route as MethodeRouteImport } from './routes/methode'
import { Route as OrientationRouteImport } from './routes/orientation'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as RecruteursRouteImport } from './routes/recruteurs'
import { Route as TalentsRouteImport } from './routes/talents'
import { Route as AuthenticatedEspaceRouteImport } from './routes/_authenticated/espace'
import { Route as OffresIndexRouteImport } from './routes/offres/index'
import { Route as OffresJobIdRouteImport } from './routes/offres/$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcheRoute = MarcheRouteImport.update({
  id: '/marche',
  path: '/marche',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodeRoute = MethodeRouteImport.update({
  id: '/methode',
  path: '/methode',
  getParentRoute: () => rootRouteImport,
} as any)
const OrientationRoute = OrientationRouteImport.update({
  id: '/orientation',
  path: '/orientation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruteursRoute = RecruteursRouteImport.update({
  id: '/recruteurs',
  path: '/recruteurs',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentsRoute = TalentsRouteImport.update({
  id: '/talents',
  path: '/talents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEspaceRoute = AuthenticatedEspaceRouteImport.update({
  id: '/espace',
  path: '/espace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const OffresIndexRoute = OffresIndexRouteImport.update({
  id: '/offres/',
  path: '/offres/',
  getParentRoute: () => rootRouteImport,
} as any)
const OffresJobIdRoute = OffresJobIdRouteImport.update({
  id: '/offres/$jobId',
  path: '/offres/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/marche': typeof MarcheRoute
  '/methode': typeof MethodeRoute
  '/orientation': typeof OrientationRoute
  '/profil': typeof ProfilRoute
  '/recruteurs': typeof RecruteursRoute
  '/talents': typeof TalentsRoute
  '/espace': typeof AuthenticatedEspaceRoute
  '/offres/$jobId': typeof OffresJobIdRoute
  '/offres/': typeof OffresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/marche': typeof MarcheRoute
  '/methode': typeof MethodeRoute
  '/orientation': typeof OrientationRoute
  '/profil': typeof ProfilRoute
  '/recruteurs': typeof RecruteursRoute
  '/talents': typeof TalentsRoute
  '/espace': typeof AuthenticatedEspaceRoute
  '/offres/$jobId': typeof OffresJobIdRoute
  '/offres': typeof OffresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/marche': typeof MarcheRoute
  '/methode': typeof MethodeRoute
  '/orientation': typeof OrientationRoute
  '/profil': typeof ProfilRoute
  '/recruteurs': typeof RecruteursRoute
  '/talents': typeof TalentsRoute
  '/_authenticated/espace': typeof AuthenticatedEspaceRoute
  '/offres/$jobId': typeof OffresJobIdRoute
  '/offres/': typeof OffresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/marche'
    | '/methode'
    | '/orientation'
    | '/profil'
    | '/recruteurs'
    | '/talents'
    | '/espace'
    | '/offres/$jobId'
    | '/offres/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/marche'
    | '/methode'
    | '/orientation'
    | '/profil'
    | '/recruteurs'
    | '/talents'
    | '/espace'
    | '/offres/$jobId'
    | '/offres'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/marche'
    | '/methode'
    | '/orientation'
    | '/profil'
    | '/recruteurs'
    | '/talents'
    | '/_authenticated/espace'
    | '/offres/$jobId'
    | '/offres/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MarcheRoute: typeof MarcheRoute
  MethodeRoute: typeof MethodeRoute
  OrientationRoute: typeof OrientationRoute
  ProfilRoute: typeof ProfilRoute
  RecruteursRoute: typeof RecruteursRoute
  TalentsRoute: typeof TalentsRoute
  OffresJobIdRoute: typeof OffresJobIdRoute
  OffresIndexRoute: typeof OffresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marche': {
      id: '/marche'
      path: '/marche'
      fullPath: '/marche'
      preLoaderRoute: typeof MarcheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methode': {
      id: '/methode'
      path: '/methode'
      fullPath: '/methode'
      preLoaderRoute: typeof MethodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orientation': {
      id: '/orientation'
      path: '/orientation'
      fullPath: '/orientation'
      preLoaderRoute: typeof OrientationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruteurs': {
      id: '/recruteurs'
      path: '/recruteurs'
      fullPath: '/recruteurs'
      preLoaderRoute: typeof RecruteursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talents': {
      id: '/talents'
      path: '/talents'
      fullPath: '/talents'
      preLoaderRoute: typeof TalentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/espace': {
      id: '/_authenticated/espace'
      path: '/espace'
      fullPath: '/espace'
      preLoaderRoute: typeof AuthenticatedEspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/offres/': {
      id: '/offres/'
      path: '/offres'
      fullPath: '/offres/'
      preLoaderRoute: typeof OffresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offres/$jobId': {
      id: '/offres/$jobId'
      path: '/offres/$jobId'
      fullPath: '/offres/$jobId'
      preLoaderRoute: typeof OffresJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEspaceRoute: typeof AuthenticatedEspaceRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEspaceRoute: AuthenticatedEspaceRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MarcheRoute: MarcheRoute,
  MethodeRoute: MethodeRoute,
  OrientationRoute: OrientationRoute,
  ProfilRoute: ProfilRoute,
  RecruteursRoute: RecruteursRoute,
  TalentsRoute: TalentsRoute,
  OffresJobIdRoute: OffresJobIdRoute,
  OffresIndexRoute: OffresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
