/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OffresIndexRouteImport } from './routes/offres/index'
import { Route as OffresJobIdRouteImport } from './routes/offres/$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OffresIndexRoute = OffresIndexRouteImport.update({
  id: '/offres/',
  path: '/offres/',
  getParentRoute: () => rootRouteImport,
} as any)
const OffresJobIdRoute = OffresJobIdRouteImport.update({
  id: '/offres/$jobId',
  path: '/offres/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/offres/$jobId': typeof OffresJobIdRoute
  '/offres/': typeof OffresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/offres/$jobId': typeof OffresJobIdRoute
  '/offres': typeof OffresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/offres/$jobId': typeof OffresJobIdRoute
  '/offres/': typeof OffresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/offres/$jobId' | '/offres/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/offres/$jobId' | '/offres'
  id: '__root__' | '/' | '/offres/$jobId' | '/offres/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OffresJobIdRoute: typeof OffresJobIdRoute
  OffresIndexRoute: typeof OffresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offres/': {
      id: '/offres/'
      path: '/offres'
      fullPath: '/offres/'
      preLoaderRoute: typeof OffresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offres/$jobId': {
      id: '/offres/$jobId'
      path: '/offres/$jobId'
      fullPath: '/offres/$jobId'
      preLoaderRoute: typeof OffresJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OffresJobIdRoute: OffresJobIdRoute,
  OffresIndexRoute: OffresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
