/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarcheRouteImport } from './routes/marche'
import { Route as OrientationRouteImport } from './routes/orientation'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as RecruteursRouteImport } from './routes/recruteurs'
import { Route as OffresIndexRouteImport } from './routes/offres/index'
import { Route as OffresJobIdRouteImport } from './routes/offres/$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcheRoute = MarcheRouteImport.update({
  id: '/marche',
  path: '/marche',
  getParentRoute: () => rootRouteImport,
} as any)
const OrientationRoute = OrientationRouteImport.update({
  id: '/orientation',
  path: '/orientation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruteursRoute = RecruteursRouteImport.update({
  id: '/recruteurs',
  path: '/recruteurs',
  getParentRoute: () => rootRouteImport,
} as any)
const OffresIndexRoute = OffresIndexRouteImport.update({
  id: '/offres/',
  path: '/offres/',
  getParentRoute: () => rootRouteImport,
} as any)
const OffresJobIdRoute = OffresJobIdRouteImport.update({
  id: '/offres/$jobId',
  path: '/offres/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/marche': typeof MarcheRoute
  '/orientation': typeof OrientationRoute
  '/profil': typeof ProfilRoute
  '/recruteurs': typeof RecruteursRoute
  '/offres/$jobId': typeof OffresJobIdRoute
  '/offres/': typeof OffresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/marche': typeof MarcheRoute
  '/orientation': typeof OrientationRoute
  '/profil': typeof ProfilRoute
  '/recruteurs': typeof RecruteursRoute
  '/offres/$jobId': typeof OffresJobIdRoute
  '/offres': typeof OffresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/marche': typeof MarcheRoute
  '/orientation': typeof OrientationRoute
  '/profil': typeof ProfilRoute
  '/recruteurs': typeof RecruteursRoute
  '/offres/$jobId': typeof OffresJobIdRoute
  '/offres/': typeof OffresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/marche'
    | '/orientation'
    | '/profil'
    | '/recruteurs'
    | '/offres/$jobId'
    | '/offres/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/marche'
    | '/orientation'
    | '/profil'
    | '/recruteurs'
    | '/offres/$jobId'
    | '/offres'
  id:
    | '__root__'
    | '/'
    | '/marche'
    | '/orientation'
    | '/profil'
    | '/recruteurs'
    | '/offres/$jobId'
    | '/offres/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarcheRoute: typeof MarcheRoute
  OrientationRoute: typeof OrientationRoute
  ProfilRoute: typeof ProfilRoute
  RecruteursRoute: typeof RecruteursRoute
  OffresJobIdRoute: typeof OffresJobIdRoute
  OffresIndexRoute: typeof OffresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marche': {
      id: '/marche'
      path: '/marche'
      fullPath: '/marche'
      preLoaderRoute: typeof MarcheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orientation': {
      id: '/orientation'
      path: '/orientation'
      fullPath: '/orientation'
      preLoaderRoute: typeof OrientationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruteurs': {
      id: '/recruteurs'
      path: '/recruteurs'
      fullPath: '/recruteurs'
      preLoaderRoute: typeof RecruteursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offres/': {
      id: '/offres/'
      path: '/offres'
      fullPath: '/offres/'
      preLoaderRoute: typeof OffresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offres/$jobId': {
      id: '/offres/$jobId'
      path: '/offres/$jobId'
      fullPath: '/offres/$jobId'
      preLoaderRoute: typeof OffresJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarcheRoute: MarcheRoute,
  OrientationRoute: OrientationRoute,
  ProfilRoute: ProfilRoute,
  RecruteursRoute: RecruteursRoute,
  OffresJobIdRoute: OffresJobIdRoute,
  OffresIndexRoute: OffresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
